name: test-fail

on:  
  push:
  pull_request:
    branches:
      - staging
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST1 }}
        username: ${{ secrets.USERNAME1 }}
        password: ${{ secrets.PASSWORD1 }}
        port: ${{ secrets.PORT1 }}
        gituser: ${{ secrets.GIT_USER }}
        token: ${{ secrets.GIT_TOKEN }}
        script: |
          cd /opt/branching
          echo ${{ secrets.PASSWORD }} | sudo -S git checkout staging
          echo ${{ secrets.PASSWORD }} | sudo -S git pull
          
          
        

    
